### ISSUE TITLE
Support setting stdout stream via string such as ext://sys.stdout

### ISSUE THREAD

**Issue by czchen** [trentm/node-bunyan#243]
To set output stream to stdout, the current configuration needs to set `stream` to `process.stdout`. This is easy if the configuration is written as code, but hard if the configuration is written as file like `config.json`. If I read bunyan configuration from file, I don't know how to set `stream` to stdout without writing some convert code.

It would be more convenience if bunyan can use a string like `ext://sys.stdout` as `process.stdout`. The string `ext://sys.stdout` is from Python logging module, and other name is also good for me.

**Comment by trentm** [comment]
Thanks for the ticket. Hm, okay, this isn't the first time this has come up. I resisted before because I was leery of a separate "language" for that field. Just stdout/stderr is reasonable though so I agree there should be some way to spell this in config.

"sys.stdout" is specific to Python.  Thanks for mentioning the Python usage tho, that helps a lot!  I can't find any docs/hits for "python logging ext://sys.stdout" on Google. Do you have an links to docs on that usage in Python? Example code? Thanks.

**Comment by czchen** [comment]
It is in the example section in <https://docs.python.org/3/library/logging.config.html#dictionary-schema-details>.

```yaml
handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
    filters: [allow_foo]
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    filename: logconfig.log
    maxBytes: 1024
    backupCount: 3
```
